replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

arguments:
  time: 30
  cpu: 80
  ram: 80
  minioHost:
  minioAccessKey:
  minioSecretKey:
  minioBucketCount: 5
  minioFileCount: 5
  minioMinSize: 2
  minioMaxSize: 20
  storageProccessCount: 10
  storageFileCount: 10
  storageMinSize: 10
  storageMaxSize: 100

resources:
  limits:
    cpu: "4"
    memory: "8192Mi"
    ephemeral-storage: "600Mi"
  requests:
    cpu: "3"
    memory: "7168Mi"
    ephemeral-storage: "500Mi"
